/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_man_JNI_CPP */

#ifndef _Included_com_man_JNI_CPP
#define _Included_com_man_JNI_CPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_man_JNI_CPP
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_man_JNI_1CPP_printText
  (JNIEnv *, jobject);

/*
 * Class:     com_man_JNI_CPP
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_man_JNI_1CPP_mul
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
